<?php

declare(strict_types=1);

namespace App\Tests\Unit\ProfileFeature\Domain\Interactor;

use App\ProfileFeature\Domain\Entity\Profile;
use App\ProfileFeature\Domain\Event\ProfileCreated;
use App\ProfileFeature\Domain\Interactor\CreateProfileInteractor;
use App\ProfileFeature\Domain\Port\ClockInterface;
use App\ProfileFeature\Domain\Port\DomainEventDispatcherInterface;
use App\ProfileFeature\Domain\Repository\ProfileRepositoryInterface;
use App\ProfileFeature\Domain\ValueObject\Username;
use PHPUnit\Framework\TestCase;

final class CreateProfileInteractorTest extends TestCase
{
    private ClockInterface $clock;
    private DomainEventDispatcherInterface $eventDispatcher;

    protected function setUp(): void
    {
        $this->clock = $this->createStub(ClockInterface::class);
        $this->clock->method('now')->willReturn(new \DateTimeImmutable('2024-01-01 12:00:00'));
        $this->eventDispatcher = $this->createStub(DomainEventDispatcherInterface::class);
    }

    public function testCreateSavesProfile(): void
    {
        $profiles = $this->createMock(ProfileRepositoryInterface::class);
        $profiles->method('findByUserId')->willReturn(null);
        $profiles->expects($this->once())->method('save');

        (new CreateProfileInteractor($profiles, $this->clock, $this->eventDispatcher))->create('user-1');
    }

    public function testCreateThrowsWhenProfileAlreadyExists(): void
    {
        $existing = Profile::create('user-1', Username::fromString('user_abc'), new \DateTimeImmutable());

        $profiles = $this->createStub(ProfileRepositoryInterface::class);
        $profiles->method('findByUserId')->willReturn($existing);

        $this->expectException(\DomainException::class);

        (new CreateProfileInteractor($profiles, $this->clock, $this->eventDispatcher))->create('user-1');
    }

    public function testCreateDoesNotSaveWhenProfileAlreadyExists(): void
    {
        $existing = Profile::create('user-1', Username::fromString('user_abc'), new \DateTimeImmutable());

        $profiles = $this->createMock(ProfileRepositoryInterface::class);
        $profiles->method('findByUserId')->willReturn($existing);
        $profiles->expects($this->never())->method('save');

        try {
            (new CreateProfileInteractor($profiles, $this->clock, $this->eventDispatcher))->create('user-1');
        } catch (\DomainException) {
        }
    }

    public function testCreatedProfileHasAutoGeneratedUsername(): void
    {
        $saved = null;
        $profiles = $this->createStub(ProfileRepositoryInterface::class);
        $profiles->method('findByUserId')->willReturn(null);
        $profiles->method('save')->willReturnCallback(function (Profile $p) use (&$saved) {
            $saved = $p;
        });

        (new CreateProfileInteractor($profiles, $this->clock, $this->eventDispatcher))->create('user-1');

        $this->assertNotNull($saved);
        $this->assertStringStartsWith('user_', $saved->username()?->value() ?? '');
    }

    public function testCreateDispatchesProfileCreatedEvent(): void
    {
        $profiles = $this->createStub(ProfileRepositoryInterface::class);
        $profiles->method('findByUserId')->willReturn(null);

        $dispatcher = $this->createMock(DomainEventDispatcherInterface::class);
        $dispatcher->expects($this->once())
            ->method('dispatch')
            ->with($this->isInstanceOf(ProfileCreated::class));

        (new CreateProfileInteractor($profiles, $this->clock, $dispatcher))->create('user-1');
    }
}
