services:
  php:
    build: ./docker/php
    environment:
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE:-30M}
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT}"
    environment:
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE:-30M}
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - php
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-data/data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}"
      - "${RABBITMQ_PORT_MANAGEMENT}"
  mercure:
    image: dunglas/mercure
    environment:
      SERVER_NAME: '${SERVER_NAME}'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_PUBLISHER_JWT_KEY}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_SUBSCRIBER_JWT_KEY}'
      MERCURE_EXTRA_DIRECTIVES: anonymous
  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "${CLICKHOUSE_PORT}"
      - "${CLICKHOUSE_NATIVE_PORT}"
  manticore:
    image: manticoresearch/manticore
    volumes:
      - ./volumes/manticore-data:/var/lib/manticore
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  consumer:
    build: ./docker/php
    command: php bin/console messenger:consume async --time-limit=3600
    environment:
      UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE:-30M}
    volumes:
      - .:/var/www/html
    depends_on:
      - rabbitmq
    restart: unless-stopped
