# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

user_controllers:
    resource:
        path: ../src/UserFeature/Presentation/Controller/
        namespace: App\UserFeature\Presentation\Controller
    type: attribute

profile_controllers:
    resource:
        path: ../src/ProfileFeature/Presentation/Controller/
        namespace: App\ProfileFeature\Presentation\Controller
    type: attribute

team_controllers:
    resource:
        path: ../src/TeamFeature/Presentation/Controller/
        namespace: App\TeamFeature\Presentation\Controller
    type: attribute

workflow_controllers:
    resource:
        path: ../src/WorkflowFeature/Presentation/Controller/
        namespace: App\WorkflowFeature\Presentation\Controller
    type: attribute
